# Generated by Django 5.0 on 2023-12-16 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordstore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='title',
            new_name='artist',
        ),
    ]
