# Generated by Django 6.0.5 on 2026-05-31 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordstore', '0002_rename_title_record_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='rel_date',
            field=models.DateField(),
        ),
        migrations.RemoveField(
            model_name='store',
            name='records',
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordstore.record')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordstore.store')),
            ],
            options={
                'unique_together': {('store', 'record')},
            },
        ),
        migrations.AddField(
            model_name='store',
            name='records',
            field=models.ManyToManyField(blank=True, through='recordstore.Inventory', to='recordstore.record'),
        ),
    ]
